Knjiznica/Models/Rezervacija.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Knjiznica.Models
{
    public class Rezervacija
    {
        public int RezervacijaID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string NaslovKnjige { get; set; }
        public string Seminar { get; set; }
        public string Status { get; set; }
        public int PosudbaID { get; set; }

        public Rezervacija()
        {

        }

        public Rezervacija(int rezervacijaID, string ime, string prezime, string naslovKnjige, int posudbaID)
        {
            this.RezervacijaID = rezervacijaID;
            this.Ime = ime;
            this.Prezime = prezime;
            this.NaslovKnjige = naslovKnjige;
            this.PosudbaID = posudbaID;
        }

        public Rezervacija(int rezervacijaID, string ime, string prezime, string naslovKnjige, string seminar, string status, int posudbaID)
        {
            this.RezervacijaID = rezervacijaID;
            this.Ime = ime;
            this.Prezime = prezime;
            this.NaslovKnjige = naslovKnjige;
            this.Seminar = seminar;
            this.Status = status;
            this.PosudbaID = posudbaID;
        }


        public Rezervacija(string ime, string prezime, string naslovKnjige, string seminar, string status)
        {
            
            this.Ime = ime;
            this.Prezime = prezime;
            this.NaslovKnjige = naslovKnjige;
            this.Seminar = seminar;
            this.Status = status;
        }



    }
}

Knjiznica/Controllers/PregledController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using Knjiznica.Models;
using System.Data;
using System.Web.Configuration;


namespace Knjiznica.Controllers
{
    public class PregledController : Controller
    {

        private List<Zaposlenik> noviZaposlenik = new List<Zaposlenik>();

        private List<Knjiga> ListaKnjiga = new List<Knjiga>();


        private List<Rezervacija> ListaRezervacija = new List<Rezervacija>();


        private string ConnStr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        // GET: Pregled
        public ActionResult Index()
        {

            return View();
        }


        

              public ActionResult PopisSlobodnihKnjiga()
        {

           

            string freeBooksQuery = "SELECT * FROM slobodne_knjige2";

           

            using (SqlConnection connection = new SqlConnection(ConnStr))
            {
                SqlCommand command = new SqlCommand(freeBooksQuery, connection);

                try
                {
                    connection.Open();
                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        Debug.WriteLine("\t{0}\t{1}\t{2}t{3}\t{4}\t{5}\t{6}",
                            reader[0], reader[1], reader[2], reader[3], reader[4], reader[5], reader[6]);

                        ListaKnjiga.Add(new Knjiga(Int32.Parse(reader[0].ToString()), reader[1].ToString(), reader[2].ToString(),
                            reader[3].ToString(), Int32.Parse(reader[4].ToString()), Int32.Parse(reader[5].ToString()), Int32.Parse(reader[5].ToString())));
                    }
                    reader.Close();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
            
            return View(ListaKnjiga);
        }



        public ActionResult PretraziSlobodneKnjige(FormCollection form)
        {
            string slobodnaKnjiga = form["slobodnaKnjiga"];
       


            string freeBooksQuery = "SELECT * FROM slobodne_knjige2 WHERE NaslovKnjige=@slobodnaKnjiga";

            

            using (SqlConnection connection = new SqlConnection(ConnStr))
            {
                SqlCommand command = new SqlCommand(freeBooksQuery, connection);
                command.Parameters.Add("@slobodnaKnjiga", SqlDbType.VarChar, 50).Value = slobodnaKnjiga;

                try
                {
                    connection.Open();
                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        Debug.WriteLine("\t{0}\t{1}\t{2}t{3}\t{4}\t{5}\t{6}",
                            reader[0], reader[1], reader[2], reader[3], reader[4], reader[5], reader[6]);

                        ListaKnjiga.Add(new Knjiga(Int32.Parse(reader[0].ToString()), reader[1].ToString(), reader[2].ToString(),
                            reader[3].ToString(), Int32.Parse(reader[4].ToString()), Int32.Parse(reader[5].ToString()), Int32.Parse(reader[5].ToString())));
                    }
                    reader.Close();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }




            return View(ListaKnjiga);
        }


        public ActionResult NajpopularnijeKnjige()
        {

           

           
            return View();


        }


        public ActionResult Rezervacija(int id)
        {
            Debug.WriteLine("NUTRA SAM " + id);
            return View();  
        }

        [HttpPost]
        public ActionResult RezervacijaStatus(FormCollection form, int test)
        {
            int knjigaID = test;

            // TODO: Back end validation

            Clan clan = new Clan(form["Ime"], form["Prezime"], form["Adresa"],
                form["Email"], form["Telefon"]);

            Debug.WriteLine("IME: " + clan.Ime);
            Debug.WriteLine("PREZIME: " + clan.Prezime);
            Debug.WriteLine("ADRESA: " + clan.AdresaStanovanja);
            Debug.WriteLine("EMAIL: " + clan.Email);
            Debug.WriteLine("TELEFON: " + clan.Telefon);

            using (SqlConnection connection = new SqlConnection(ConnStr))
            {
                try
                {
                    connection.Open();

                    SqlCommand command = new SqlCommand("INSERT INTO Clanovi(Ime, Prezime, AdresaStanovanja, Email, Telefon) output INSERTED.ClanID VALUES (@Ime, @Prezime, @Adresa, @Email, @Telefon)", connection);
                  
                    command.Parameters.Add("@Ime", SqlDbType.VarChar, 50).Value = clan.Ime;
                    command.Parameters.Add("@Prezime", SqlDbType.VarChar, 50).Value = clan.Prezime;
                    command.Parameters.Add("@Adresa", SqlDbType.VarChar, 100).Value = clan.AdresaStanovanja;
                    command.Parameters.Add("@Email", SqlDbType.VarChar, 50).Value = clan.Email;
                    command.Parameters.Add("@Telefon", SqlDbType.VarChar, 50).Value = clan.Telefon;

                    int clanID = (int)command.ExecuteScalar();
           
                    Debug.WriteLine(clanID);

                    Debug.WriteLine("Uspješno upisan novi član!");

                    connection.Close();

                    /****************************POSUDBA******************************/

                    Posudba posudba = new Posudba(clanID, knjigaID);

                    Debug.WriteLine(posudba.ClanID);
                    Debug.WriteLine(posudba.KnjigaID);

                    connection.Open();

                    SqlCommand command2 = new SqlCommand("INSERT INTO Posudba(ClanID, KnjigaID) output INSERTED.PosudbaID VALUES (@ClanID, @KnjigaID)", connection);
                   
                    //dodati upis za rezervacijas

                    command2.Parameters.Add("ClanID", SqlDbType.Int, 16).Value = posudba.ClanID;
                    command2.Parameters.Add("KnjigaID", SqlDbType.Int, 16).Value = posudba.KnjigaID;

                    int posudbaId = (int)command2.ExecuteScalar();

                    Debug.WriteLine("Uspješno upisana nova posudba!");

                    connection.Close();

                    /****************************RezervacijaKnjiga******************************/
                    connection.Open();

                    SqlCommand command3 = new SqlCommand("INSERT INTO RezervacijaKnjiga(Ime,Prezime, KnjigaID, PosudbaID) VALUES (@Ime, @Prezime, @KnjigaID, @PosudbaID)", connection);
                  
                    command3.Parameters.Add("@Ime", SqlDbType.VarChar, 50).Value = clan.Ime;
                    command3.Parameters.Add("@Prezime", SqlDbType.VarChar, 50).Value = clan.Prezime;
                    command3.Parameters.Add("@KnjigaID", SqlDbType.Int, 16).Value = posudba.KnjigaID;
                    command3.Parameters.Add("@PosudbaID", SqlDbType.Int, 16).Value = posudbaId;

                    command3.ExecuteNonQuery();

                    Debug.WriteLine("Uspješno upisana nova rezervacija!");

                    connection.Close();


                    /****************************PromjenaUKnjizi******************************/
                    connection.Open();

                    SqlCommand command4 = new SqlCommand("UPDATE Knjige SET BrojPosudba = BrojPosudba + 1 WHERE KnjigaID = @KnjigaID", connection);
                    command4.Parameters.Add("@KnjigaID", SqlDbType.Int, 16).Value = posudba.KnjigaID;
                    command4.ExecuteNonQuery();
                    Debug.WriteLine("Uspješno updejtan broj posudbi knjige!");
                    connection.Close();



                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }








            }





            return View();
        }


        //REGISTRATIONS

       
        public ActionResult Registracija()
        {
   
            return View();
        }


        [HttpPost]
       
        public ActionResult RegistracijaUspjesna(FormCollection form)
        {
            Zaposlenik zaposlenik = new Zaposlenik(form["KorisnickoIme"], form["Lozinka"]);

            Debug.WriteLine("Korisnicko ime: " + zaposlenik.KorisnickoIme);
            Debug.WriteLine("Lozinka: " + zaposlenik.Lozinka);

            using (SqlConnection connection = new SqlConnection(ConnStr))
            {
                try
                {

                    connection.Open();



                    SqlCommand command = new SqlCommand("INSERT INTO Zaposlenici VALUES (@KorisnickoIme, @Lozinka)", connection);


                    command.Parameters.Add("@KorisnickoIme", SqlDbType.VarChar, 50).Value = zaposlenik.KorisnickoIme;
                    command.Parameters.Add("@Lozinka", SqlDbType.VarChar, 50).Value = zaposlenik.Lozinka;

                    command.ExecuteNonQuery();




                    Debug.WriteLine("Uspješno upisan novi zaposlenik!");

                    connection.Close();




                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

            }


                return View();
        }


        public ActionResult Prijava()
        {
            return View();
        }

      

        [HttpPost]
        public ActionResult PrijavaUspjesna(FormCollection form)
        {
            string korisnickoIme = form["KorisnickoIme"];
            string lozinka = form["Lozinka"];

            Debug.WriteLine("Korisnicko ime: " + korisnickoIme);
            Debug.WriteLine("Lozinka: " + lozinka);

Knjiznica/Views/Pregled/Index.cshtml
@model IEnumerable<Knjiznica.Models.Knjiga>

@{
    ViewBag.Title = "Index";
    ViewBag.datum = DateTime.Now;
}



<br />


@using (Html.BeginForm("PretraziSlobodneKnjige", "Pregled", FormMethod.Post))
{

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-7"> <h4> Danas je  @ViewBag.datum.</h4></div>

            <div class="col-sm-5">

                Pretraga po naslovu knjige


                @Html.TextBox("slobodnaKnjiga")
      
                <input type="submit" value="Pretraži" class="btn btn-link" />
           


            </div>
        </div>
    </div>
    <br>
    <div class="container-fluid">

        <p style="font-family:Comic Sans MS, cursive, sans-serif; font-size:20px">
            “Good friends, good books, and a sleepy conscience: this is the ideal life.”

        </p>

        <p style="font-family:Comic Sans MS, cursive, sans-serif; font-size:15px">
            ― Mark Twain
        </p>


        <hr>

        <h5>
            U knjižnici možete posuđivati te rezervirati knjige koje su slobodne.
            <br />Ako ste naš član dovoljno je samo da rezervirate knjigu.
            <br />Ako niste naš član potrebno je obaviti registraciju na stranici kako biste mogli nastaviti s posudbom.
            <br />Posudbe će obaviti osoblje knjižnice te je na vama samo da preuzmete knjigu.
            <br />
            Uživajte u izboru i nadamo se da ćete pronaći knjigu po svojem ukusu!
        </h5>
        <h5>Ugodnu zabavu želi vam društvo Hrvatskih ljubitelja knjiga!</h5>
    </div>

    <hr />





}




<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">

           
            <h4 style="text-align:center">

                <span class="glyphicon glyphicon-search"></span>
                Logiraj se kao korisnik
            </h4>

            <div class="btn-group" role="group" aria-label="Prijava i registracija" style="margin-left:40%">
                <button type="button" class="btn btn-warning">
                    @Html.ActionLink("Prijava", "Prijava", null, new { @style = "color:#000000;" })
                </button>
               

            </div>





        </div>
        <div class="col-sm-4">

            
            <h4 style="text-align:center">
                <span class="glyphicon glyphicon-search"></span>
            Posudi knjigu</h4>

            <button type="button" class="btn btn-warning" style="margin-left:32%">
                @Html.ActionLink("Slobodne knjige", "PopisSlobodnihKnjiga", null, new { @style = "color:#000000;" })

            </button>


        </div>
        <div class="col-sm-4">

            

            <h4 style="text-align:center">
                <span class="glyphicon glyphicon-search"></span>
            TOP liste - popisi</h4>


            <div class="btn-group" role="group" aria-label="Knjige" style="margin-left:5%">
                <button type="button" class="btn btn-warning">
                    @Html.ActionLink("Knjige od A do Ž", "KnjigePoAbecedi", null, new { @style = "color:#000000;" })

                </button>
                <button type="button" class="btn btn-warning">
                    @Html.ActionLink("Popis najpopularnijih knjiga", "NajpopularnijeKnjige", null, new { @style = "color:#000000;" })
                </button>

            </div>


        </div>
    </div>
</div>

<br />
<br />

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          
            <div class="caption">
                <h3 style="text-align:center">Pročitaj najnovije vijesti</h3>
                <br />
              
                <p style="text-align:center"> <a href="#" class="btn btn-default" role="button">Saznaj više</a></p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
      
            <div class="caption">
                <h3 style="text-align:center">Uključi se u raspravu</h3>
                <br />
          
                <p style="text-align:center"> <a href="#" class="btn btn-default" role="button">Saznaj više</a></p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
  
            <div class="caption">
                <h3 style="text-align:center">Pogledaj video</h3>
                <br />
             
                <p style="text-align:center"> <a href="#" class="btn btn-default" role="button">Saznaj više</a></p>
            </div>
        </div>
    </div>


</div>



<br />
<br />
<br />
<div></div>

    <img src="/Image/test.jpg" />

Knjiznica/Views/Pregled/IzbrisiKnjigu.cshtml
@{
    ViewBag.Title = "IzbrisiKnjigu";
}

<br />

<p>Knjiga @ViewBag.naslov je izbrisana!</p>

@Html.ActionLink("Povratak", "Knjige")

Knjiznica/Views/Pregled/IzbrisiRezervaciju.cshtml
@{
    ViewBag.Title = "IzbrisiRezervaciju";
}

<h2>Rezervacija</h2>

<br />
<div>
    <p>
       Rezervacija je uspješni izbrisana.
    </p>
</div>
<div>
    @Html.ActionLink("Povratak na rezervacije", "PregledRezervacija")
</div>

Knjiznica/Views/Pregled/IzmijeniKnjigu.cshtml
@model IEnumerable<Knjiznica.Models.Knjiga>


@{
    ViewBag.Title = "IzmijeniKnjigu";

}

<h2>Detalji o knjizi</h2>




@using (Html.BeginForm("IzmijenjenaKnjiga", "Pregled", new { knjigaID = @ViewBag.knjigaID }, FormMethod.Post))
{
    @Html.ValidationSummary(true)





    <dt>
        Naslov knjige
    </dt>
    <dd>


        @Html.TextBox("naslovKnjige", (string)ViewBag.naslov)





    </dd>
    <dd>

        @Html.ValidationMessage("naslov", "Naslov ne može biti veći od 50 znakova", new { style = "color:red"})
    </dd>

    <br />

    <dt>
        Opis
    </dt>
    <dd>





        @Html.TextArea("opisKnjige", (string)ViewBag.opis, new { style = "width:500px; height:150px; wrap:hard; rows:10;cols:20" })







    </dd>

    <dd>

        @Html.ValidationMessage("opis", "Opis ne može biti veći od 250 znakova", new { style = "color:red" })

    </dd>
    <br />




    <dt>
        Posudbe
    </dt>
    <dd>



        @Html.TextBox("brojPosudba", (int)ViewBag.brojPosudba)


    </dd>

    <dd>
        @Html.ValidationMessage("posudba", "Broj posudbi ne može biti veći od broja knjiga", new { style = "color:red" })
    </dd>
    <br />

    <dt>
        Ukupan broj knjiga
    </dt>
    <dd>



        @Html.TextBox("brojKnjiga", (int)ViewBag.brojKnjiga)



    </dd>

    <dd>
        @Html.ValidationMessage("knjiga", "Broj knjiga ne može biti manji od broja posudbi", new { style = "color:red" })
    </dd>
    <br />


    <dt>
        Zatvoren
    </dt>
    <dd>


   

        @Html.CheckBox("Zatvoren", false)


    </dd>

    <dd>
        @Html.ValidationMessage("zatvoren", "OBAVEZNO zatvaranje knjige ako je broj posudbi jednak broju knjiga", new { style = "color:red" })
    </dd>
    <br />





    <input type="submit" value="Upiši izmjenu" style="color:#428bd4"/>



 


    <button type="submit" value="Izbrisi">
        @Html.ActionLink("Izbriši knjigu", "IzbrisiKnjigu", new { naslov = ViewBag.naslov })
    </button>

}


<br />

@Html.ActionLink("Povratak", "Knjige")

Knjiznica/Views/Pregled/IzmijenjenaRezervacija.cshtml
@{
    ViewBag.Title = "IzmijenjenaRezervacija";
}

<h2>Rezervacija</h2>

<br />
<div>
    <p>
        <label class="redColor">@ViewBag.Poruka</label>
    </p>
</div>
<div>
    @Html.ActionLink("Povratak na rezervacije", "PregledRezervacija")
</div>

Knjiznica/Views/Pregled/KnjigaIzdana.cshtml
@model Knjiznica.Models.Knjiga
@{
    ViewBag.Title = "KnjigaIzdana";
}

<h2>KnjigaIzdana</h2>


<style>
    label {
        display: inline-block;
        width: 150px;
        margin: 5px;
        font-weight: bold;
    }
</style>

<h3>Račun @Html.DisplayFor(x => x.NaslovKnjige) izdan!</h3>

<br />

<h3>Podaci računa: </h3>

<hr />

<div>
    @Html.LabelFor(x => x.NaslovKnjige)
    @Html.DisplayFor(x => x.NaslovKnjige)
</div>

<div>
    @Html.LabelFor(x => x.ImePisca)
    @Html.DisplayFor(x => x.ImePisca)
</div>
<div>
    @Html.LabelFor(x => x.PrezimePisca)
    @Html.DisplayFor(x => x.PrezimePisca)
</div>
<div>
    @Html.LabelFor(x => x.GodinaIzdanja)
    @Html.DisplayFor(x => x.GodinaIzdanja)
</div>
<div>
    @Html.LabelFor(x => x.Opis)
    @Html.DisplayFor(x => x.Opis)
</div>
<div>
    @Html.LabelFor(x => x.BrojKnjiga)
    @Html.DisplayFor(x => x.BrojKnjiga)
</div>

Knjiznica/Views/Pregled/NeodobrenaRezervacija.cshtml
@model IEnumerable<Knjiznica.Models.Rezervacija>

@{
    ViewBag.Title = "NeodobrenaRezervacija";
}



<style>


    tr {
        border: 1px solid white !important;
    }

    th {
        border: 1px solid white !important;
    }

    td {
        border: 1px solid white !important;
    }
</style>


<h2>Popis svih neodobrenih rezervacija</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NaslovKnjige)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Seminar)
        </th>
    </tr>



    @foreach (var rez in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => rez.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => rez.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => rez.NaslovKnjige)
            </td>
            <td>
                @Html.DisplayFor(modelItem => rez.Status)

            </td>

            <td>
                @Html.DisplayFor(modelItem => rez.Seminar)

            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Povratak na rezervacije", "PregledRezervacija")
</div>

Knjiznica/Views/Pregled/OdobrenaRezervacija.cshtml
@model IEnumerable<Knjiznica.Models.Rezervacija>

@{
    ViewBag.Title = "OdobrenaRezervacija";
}


<style>


    tr {
        border: 1px solid white !important;
    }

    th {
        border: 1px solid white !important;
    }

    td {
        border: 1px solid white !important;
    }
</style>

<h2>Popis svih odobrenih rezervacija</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NaslovKnjige)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Seminar)
        </th>
    </tr>



    @foreach (var rez in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => rez.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => rez.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => rez.NaslovKnjige)
            </td>
            <td>
                @Html.DisplayFor(modelItem => rez.Status)

            </td>

            <td>
                @Html.DisplayFor(modelItem => rez.Seminar)

            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Povratak na rezervacije", "PregledRezervacija")
</div>

Knjiznica/Views/Pregled/PretraziSlobodneKnjige.cshtml
@model IEnumerable<Knjiznica.Models.Knjiga>

@{
    ViewBag.Title = "PretraziSlobodneKnjige";
}

<h2>Pretraga slobodnih knjiga za posudbu</h2>




<table class="table">
    <tr>
        <th>

            Naslov knjige
        </th>
        <th>

            Ime pisca
        </th>
        <th>

            Prezime pisca
        </th>
        <th>

            Godina izdanja
        </th>
        <th>

            Broj knjiga
        </th>



        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NaslovKnjige)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImePisca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrezimePisca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GodinaIzdanja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SlobodneKnjige)
            </td>


            <td>
                @Html.ActionLink("Rezervacija", "Rezervacija", new { id = item.KnjigaID })
            </td>
        </tr>
    }

</table>

@Html.ActionLink("Povratak", "Index")

Knjiznica/Views/Pregled/Prijava.cshtml
@{
    ViewBag.Title = "Prijava";
}

<div class="container">
    <h2>Prijava</h2>
</div>

<div class="container">

    @using (Html.BeginForm("PrijavaUspjesna", "Pregled", FormMethod.Post))
    {
        <dt>
            Upišite korisničko ime:
        </dt>
        <dd>
            <input type="text" id="" name="KorisnickoIme" />
        </dd>
        <br />

        <dt>
            Upišite lozinku:
        </dt>
        <dd>
            <input type="password" id="" name="Lozinka" />
        </dd>
        <br />


        <input type="submit" value="Prijavi se" />

    }

</div>
<br />
    <div class="container">
        @Html.ActionLink("Povratak", "Index")
    </div>

Knjiznica/Views/Pregled/PromijeniKnjigu.cshtml
@{
    ViewBag.Title = "PromijeniKnjigu";
}

<h2>Knjiga je izmijenjena</h2>

@Html.ActionLink("Povratak", "Knjige")

Knjiznica/Views/Pregled/RegistracijaUspjesna.cshtml
@{
    ViewBag.Title = "RegistracijaUspjesna";
}

<h2>Registracija je uspješna!</h2>

@Html.ActionLink("Povratak", "Index")

Knjiznica/Views/Pregled/UpisNovogClana.cshtml
@model IEnumerable<Knjiznica.Models.Zaposlenik>


@{
    ViewBag.Title = "UpisNovogClana";
}

<div class="container">

    <h2>Upis novog člana knjižnice</h2>
</div>





    @using (Html.BeginForm())

    {
        @Html.ValidationSummary()



    <dt class="container">

        Korisničko ime
    </dt>
        <dd class="container">


            @Html.TextBox("korisnickoIme")






        </dd>


        <br />


        <dt class="container">
            Lozinka
        </dt>
        <dd class="container">


            @Html.TextBox("lozinka")
        




        </dd>


        <br />


        <dt class="container">
            Ime zaposlenika
        </dt>
        <dd class="container">


            @Html.TextBox("imeZaposlenika")

          



        </dd>


        <br />

        <dt class="container">
            Prezime zaposlenika
        </dt>
        <dd class="container">


            @Html.TextBox("prezimeZaposlenika")





        </dd>


        <br />




        <dt class="container">
            Adresa zaposlenika
        </dt>
        <dd class="container">





            @Html.TextBox("adresaZaposlenika")



        </dd>



        <br />

        <dt class="container">
            Poštanski broj
        </dt>
        <dd class="container">



            @Html.TextBox("postanskiBroj")



        </dd>


        <br />

        <dt class="container">
            Odjel zaposlenika
        </dt>
        <dd class="container">



            @Html.TextBox("odjelZaposlenika")



        </dd>



        <br />



        <dt class="container">  <input type="submit" value="Upisi" /></dt>
       
      




    }


    <br />






<div class="container">
    @Html.ActionLink("Povratak na rezervacije", "PregledRezervacija")
</div>

Knjiznica/Views/Pregled/UpisiRezervacijuSaStatusom.cshtml
@{
    ViewBag.Title = "UpisiRezervacijuSaStatusom";
}

<h2>Uspješno promijenjena rezervacija</h2>

<br />
<div>
    <p>
        Dodali ste seminar i status na rezervaciju.
    </p>
</div>
<div>
    @Html.ActionLink("Povratak na rezervacije", "PregledRezervacija")
</div>